name: Android CI

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Plan CI Test
          #--tests "edu.ucsd.cse110.cse110group51.PlanTest.PlanInitializationTest"
          #        run: ./app/src/test/java/edu/ucsd/cse110/cse110group51/PlanTest.java
        run: javac app/src/test/java/edu/ucsd/cse110/cse110group51/PlanTest.java

