name: Run Search Bar Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Execute unit tests
      - name: SearchBar CI Test
        run: ./test/java/edu/ucsd/cse110/cse110group51 SearchBarTest

      # Report the results
      - name: Saerch Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless